#YML description for a namespace api-test, a deployment java-remote-debugging-test and a node port service java-remote-debugging-test

apiVersion: v1
kind: Namespace
metadata:
  name: api-test
---

apiVersion: apps/v1

kind: Deployment
metadata:
  namespace: api-test
  name: java-remote-debugging-test
  labels:
    app: java-remote-debugging-test
spec:
  replicas: 1
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: java-remote-debugging-test
  template:
    metadata:
      labels:
        app: java-remote-debugging-test
    spec:
      containers:
      - name: java-remote-debugging-test
        image: java-remote-debugging-test
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 768Mi
          requests:
            memory: 256Mi
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: "_JAVA_OPTIONS"
          value: "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8787"

---
kind: Service
apiVersion: v1
metadata:
  namespace: api-test
  name: java-remote-debugging-test
  labels:
    app: java-remote-debugging-test
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      name: https-port
      protocol: TCP
  selector:
    app: java-remote-debugging-test



